version: 0.2
env:
  shell: bash
  variables:
    STAGE: "Production"

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo $STAGE;
      - npm install -g serverless@3.28.1
  build:
    commands:
      - npm run build
      - sls plugin install -n serverless-prune-plugin --stage=$STAGE
      - sls deploy --stage=$STAGE